site_name: SUN-LAI Site
site_description: A site for my project documentation.
site_author: Your Name
site_url: https://example.com
repo_url: https://github.com/sunlai25/sunweb

# 主题设置
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

# 导航栏设置
nav:
  - 主页: index.md
  - 音乐: notion1/音乐欣赏 41c68649784c48859052b395a4a35a70.md
  - notion随笔:
      - 思考记: notion1/人生随笔 b2cd270310304cba91a36f5de685da3a.md
      - 猎象记: notion1/Untitled 1773230825a54f688313f161285fc6e6/猎象记 23548b956cdc456db2aafefa7c44918c.md
#  - 文档:
#      - 开始: docs/getting-started.md
#      - API 参考: docs/api.md
  - 构思中: docs/getting-started.md
  - 关于:
      - 概述: about/overview.md
      - 联系: contact.md
      - 团队: about/team.md

# 插件设置
plugins:
  - search
  - mkdocs-audio
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - redirects:
      redirect_maps:
        'old.md': 'new.md'
# 其他设置
extra:
  manifest: manifest.webmanifest

extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'

markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - admonition
  - def_list
  - md_in_html
  - attr_list